ybs/auth.py
# -*- encoding: utf-8 -*-
import models as m
import forms as f
from flask import session, g, Blueprint, abort, request, redirect, url_for
from render import render, wants_html
from errors import FormError
from gettext import gettext as _
from functools import wraps
from contrib.utils.form import set_form_error

def authenticate(username, password):
    user = m.User.query.filter_by(username=username).first()
    if user is None or not user.check_password(password):
        return None
    return user

def login(user):
    session['user_id'] = user.id

def logout(user):
    session.pop('user_id', None)

def get_login_user():
    user_id = session.get('user_id', None)
    if user_id:
        return m.User.query.filter_by(id=user_id).first()
    auth = request.authorization
    if auth:
        return authenticate(auth.username, auth.password)
    return None
def abort_login():
    if wants_html():
        return redirect(url_for('auth.login', next=request.full_path))
    abort(401)

def login_required(fn):
    @wraps(fn)
    def decorator(*args, **kwargs):
        if getattr(g, 'user', None) is None:
            return abort_login()
        return fn(*args, **kwargs)
    return decorator

auth_blueprint = Blueprint('auth', __name__)

@auth_blueprint.route('/login', methods=['GET', 'POST'], endpoint='login')
def login_view():
    """로그인합니다.  

    :statuscode 200: 로그인에 성공하였습니다.  로그인된 User를 반환합니다.  
    :statuscode 400: 잘못된 form을 입력했습니다. 에러가 포함된 Form을
        반환합니다.

    :query next: 로그인이 성공할 시 redirect될 URL. 

    * :class:`epicl.forms.LoginForm` 에서 request의 form을 확인하세요.  
    """
    form = f.LoginForm()
    if form.validate(template='auth/login'):
        data = form.data
        username = data['username']
        password = data['password']
        user = authenticate(username, password)
        if user is None:
            set_form_error(form, _('Invalid informations.'))
            raise FormError(form, template='auth/login')
        login(user)
        next = request.args.get('next', None)
        if next is None:
            if wants_html():
                return redirect(url_for('main.main'))
            return render(user, status=200)
        return redirect(next)
    return render(form, template='auth/login')

@auth_blueprint.route('/logout', methods=['GET'], endpoint='logout')
def logout_view():
    """로그아웃합니다.  

    :statuscode 200: 로그인에 성공하였습니다.  
    :statuscode 401: 로그인이 되어있지 않습니다.  
    """
    if not g.user:
        if wants_html():
            return redirect(url_for('auth.login'))
        return abort_login()
    logout(g.user)
    if wants_html():
        return redirect(request.referrer or url_for('main.main'))
    return render('Done', status=200)

@auth_blueprint.route('/me')
@login_required
def me():
    """로그인된 User를 반환합니다.  

    :statuscode 200: 로그인된 User를 반환합니다.  
    :statuscode 401: 로그인이 필요합니다.  
    """
    return render(g.user)

ybs/views/card_view.py
from .. import models as m
from .. import forms as f
from ..render import render, wants_html
from ..auth import login_required
from flask import Blueprint, g, abort, redirect, url_for, request
from flask.ext.negotiation import provides
from ..contrib.utils.model import slice_query, get_object_or_404

card_blueprint = Blueprint('card', __name__)

@card_blueprint.route('/card/create', methods=['GET'])
def create_form():
    form = f.CardForm()
    return render(form, template='card/create')

@card_blueprint.route('/card/', methods=['POST'])
@card_blueprint.route('/card/create', methods=['POST'])
def create():
    form = f.CardForm()
    form.validate(template='card/create')
    data = form.data

    name = data['name']
    message = data ['message']
    photo = data['photo']

    card = m.Card(
        name=name,
        message=message,
    )
    card.photo.set_original(photo)
    g.session.add(card)
    g.session.commit()
    return render(card, status=201, template='card/uploaded')

@card_blueprint.route('/card/')
@login_required
def index():
    cards = m.Card.query.all()
    return render(cards, template='card/index')

@card_blueprint.route('/card/<int:card_id>')
@login_required
def read(card_id):
    if not g.user.has_permission('card-read'):
        abort(403)
    card = get_object_or_404(m.Card, card_id)
    return render(card, template='card/read')

@card_blueprint.route('/card/<int:card_id>', methods=['DELETE'])
@login_required
def delete(card_id):
    if not g.user.has_permission('card-delete'):
        abort(403)
    card = get_object_or_404(m.Card, card_id)
    g.session.delete(card)
    g.session.commit()
    if wants_html():
        return redirect(url_for('card.index'))
    return render(None, status=204)

@card_blueprint.route('/card/confirmed')
@login_required
def confirmed():
    limit = min(request.args.get('limit', 60, type=int), 60)
    q = m.Card.query.filter_by(is_confirmed=True, is_rejected=False)
    q = q.order_by(m.Card.create_date)
    cards = slice_query(q, m.Card.create_date, m.Card, limit=limit,
        desc=False, last_id=request.args.get('last_id', None))
    return render(cards, template='card/confirmed_index')

@card_blueprint.route('/card/<int:card_id>/confirm', methods=['GET', 'POST'])
@login_required
def confirm(card_id):
    if not g.user.has_permission('card-confirm'):
        abort(403)
    card = get_object_or_404(m.Card, card_id)
    if request.method == 'POST':
        g.session.add(card)
        card.is_confirmed = True
        g.session.commit()
        return redirect(url_for('card.confirm_next'))
    return render(card, template='card/confirm')

@card_blueprint.route('/card/<int:card_id>/reject', methods=['GET', 'POST'])
@login_required
def reject(card_id):
    if not g.user.has_permission('card-confirm'):
        abort(403)
    card = get_object_or_404(m.Card, card_id)
    if request.method == 'POST':
        g.session.add(card)
        card.is_rejected = True
        g.session.commit()
        return redirect(url_for('card.confirm_next'))
    return render(card, template='card/confirm')

@card_blueprint.route('/card/confirm_next', methods=['GET', 'POST'])
@login_required
def confirm_next():
    card = m.Card.query.filter_by(
        is_confirmed=False,
        is_rejected=False
    ).order_by(
        m.Card.create_date
    ).first()
    if card is None:
        return render(None, template='card/nothing')
    return redirect(url_for('card.confirm', card_id=card.id))

ybs/templates/base/base.html
{% extends "base/master.html" %}

{% block title %}
Epicl
{% endblock title %}

{% block meta %}
  {{ super() }}
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <meta name="description" content="Epicl">
  <meta name="author" content="">
{% endblock meta %}

{% block css %}
  {{ super() }}

  <!-- Bootstrap -->
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0-wip/css/bootstrap.min.css">

  <!-- Base -->
  <link rel="stylesheet" type="text/css"
    href="{{ url_for('static',filename='css/base.css') }}" />

  <!-- Fav and touch icons -->
  <link rel="apple-touch-icon-precomposed" sizes="144x144"
    href="../assets/ico/apple-touch-icon-144-precomposed.png">
  <link rel="apple-touch-icon-precomposed" sizes="114x114"
    href="../assets/ico/apple-touch-icon-114-precomposed.png">
  <link rel="apple-touch-icon-precomposed" sizes="72x72"
    href="../assets/ico/apple-touch-icon-72-precomposed.png">
  <link rel="apple-touch-icon-precomposed"
    href="../assets/ico/apple-touch-icon-57-precomposed.png">
  <link rel="shortcut icon" href="../assets/ico/favicon.png">

  <!-- Custom CSS -->
  <style type="text/css">
  </style>
{% endblock css %}

{% block js %}
  {{ super() }}
  <!-- jQuery -->
  <script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
  <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>

  <!-- Bootstrap 3.0 -->
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0-wip/js/bootstrap.min.js"></script>

  <!-- Knockout -->
  <script src="{{ url_for('static', filename='js/knockout-2.3.0.js') }}"></script>
  
  <!-- Spin.js -->
  <script src="{{ url_for('static', filename='js/spin.min.js') }}"></script>

  <!-- Epicl utils -->
  <script language="javascript" src="{{ url_for('static', filename='js/epicl-utils.js') }}"></script>
{% endblock js %}

{% block body %}
  {{ super() }}
    {% include "base/header.html" %}
    <div id="content">
      {% block content %}
      {% endblock content %}
    </div>

    {% block after_js %}
    <!-- Le javascript ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% endblock after_js %}
{% endblock body %}

ybs/templates/base/header.html
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse"
    data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="{{ url_for('main.main') }}">인기척</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav">
      <li><a href="{{ url_for('main.main') }}">홈</a></li>
      <li><a href="{{ url_for('card.confirm_next') }}">인증</a></li>
      <li><a href="{{ url_for('card.create_form') }}">업로드</a></li>
      <li><a href="{{ url_for('card.index') }}">목록</a></li>

    </ul>
    <ul class="nav navbar-nav navbar-right">
      {% if is_loggedin() %}
      <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
      {% else %}
      <li><a href="{{ url_for('auth.login', next=request.url) }}">Login</a></li>
      {% endif %}
    </ul>

  </div><!-- /.navbar-collapse -->
</nav>

ybs/templates/base/master.html
<!DOCTYPE html>
<html lang="ko">
  <head>
    {% block meta %}
      <meta charset="utf-8">
    {% endblock meta %}

    <title>{% block title %}{% endblock %}</title>

    {% block css %}
    {% endblock css %}
    {% block js %}
    {% endblock js %}
  </head>
  <body>
    {% block body %}{% endblock %}
  </body>
</html>