ybs/views/card_view.py
from .. import models as m
from .. import forms as f
from ..render import render, wants_html
from ..auth import login_required
from flask import Blueprint, g, abort, redirect, url_for, request
from flask.ext.negotiation import provides
from ..contrib.utils.model import slice_query, get_object_or_404

card_blueprint = Blueprint('card', __name__)

@card_blueprint.route('/card/create', methods=['GET'])
def create_form():
    form = f.CardForm()
    return render(form, template='card/create')

@card_blueprint.route('/card/', methods=['POST'])
@card_blueprint.route('/card/create', methods=['POST'])
def create():
    form = f.CardForm()
    form.validate(template='card/create')
    data = form.data

    name = data['name']
    message = data ['message']
    photo = data['photo']

    card = m.Card(
        name=name,
        message=message,
    )
    card.photo.set_original(photo)
    g.session.add(card)
    g.session.commit()
    return render(card, status=201, template='card/uploaded')

@card_blueprint.route('/card/')
@login_required
def index():
    cards = m.Card.query.all()
    return render(cards, template='card/index')

@card_blueprint.route('/card/<int:card_id>')
@login_required
def read(card_id):
    if not g.user.has_permission('card-read'):
        abort(403)
    card = get_object_or_404(m.Card, card_id)
    return render(card, template='card/read')

@card_blueprint.route('/card/<int:card_id>', methods=['DELETE'])
@login_required
def delete(card_id):
    if not g.user.has_permission('card-delete'):
        abort(403)
    card = get_object_or_404(m.Card, card_id)
    g.session.delete(card)
    g.session.commit()
    if wants_html():
        return redirect(url_for('card.index'))
    return render(None, status=204)

@card_blueprint.route('/card/confirmed')
@login_required
def confirmed():
    limit = min(request.args.get('limit', 60, type=int), 60)
    q = m.Card.query.filter_by(is_confirmed=True, is_rejected=False)
    q = q.order_by(m.Card.create_date)
    cards = slice_query(q, m.Card.create_date, m.Card, limit=limit,
        desc=False, last_id=request.args.get('last_id', None))
    return render(cards, template='card/confirmed_index')

@card_blueprint.route('/card/<int:card_id>/confirm', methods=['GET', 'POST'])
@login_required
def confirm(card_id):
    if not g.user.has_permission('card-confirm'):
        abort(403)
    card = get_object_or_404(m.Card, card_id)
    if request.method == 'POST':
        g.session.add(card)
        card.is_confirmed = True
        g.session.commit()
        return redirect(url_for('card.confirm_next'))
    return render(card, template='card/confirm')

@card_blueprint.route('/card/<int:card_id>/reject', methods=['GET', 'POST'])
@login_required
def reject(card_id):
    if not g.user.has_permission('card-confirm'):
        abort(403)
    card = get_object_or_404(m.Card, card_id)
    if request.method == 'POST':
        g.session.add(card)
        card.is_rejected = True
        g.session.commit()
        return redirect(url_for('card.confirm_next'))
    return render(card, template='card/confirm')

@card_blueprint.route('/card/confirm_next', methods=['GET', 'POST'])
@login_required
def confirm_next():
    card = m.Card.query.filter_by(
        is_confirmed=False,
        is_rejected=False
    ).order_by(
        m.Card.create_date
    ).first()
    if card is None:
        return render(None, template='card/nothing')
    return redirect(url_for('card.confirm', card_id=card.id))

ybs/templates/card/confirm.html
{% extends "base/base.html" %}

{% block title %}
  Confirm
{% endblock title %}

{% block css %}
{{super()}}
<style type="text/css">
#ybs-form-confirm button{
  width: 49%;
  display: inline;
  margin :0px;
  height: 50px;
}
#ybs-form-confirm .inline-form{
  width:100%;
  display: inline;
  padding:0px;
}
</style>
{% endblock css %}

{% block body %}
    {{ super() }}
    <div class="container">
      <div class="common-form-container">
        <div class="form common-form" id="ybs-form-confirm">
          <fieldset>
            <div class="legend">
              <legend>인증</legend>  
            </div>

            <div class="form-group">
              <!-- Name -->
              <label for="ybs-form-status">상태</label>
              <div>
                {% if data.is_rejected %}
                  거절됨
                {% elif data.is_confirmed %}
                  승인됨
                {% else %}
                  확인안됨
                {% endif %}
              </div>
            </div>
            <div class="form-group">
              <!-- Name -->
              <label for="ybs-form-name">이름</label>
              <div>
                {{ data.name|safe }}
              </div>
            </div>

            <div class="form-group">
              <!-- Message -->
              <label for="ybs-form-message">메시지</label>
              <div>
                {{ data.message|safe }}
              </div>
            </div>

            <div class="form-group">
              <!-- Message -->
              <label for="ybs-form-photo">사진</label>
              <div style="text-align: center;">
                {{ data.photo.original }}
              </div>
            </div>

          </fieldset>
          <fieldset>
            <!-- Button -->
            <form class="inline-form" action="{{ url_for('card.confirm', card_id=data.id, _method='POST') }}" method="POST">
              <button class="btn btn-success">인증</button>
            </form>
            <form class="inline-form" action="{{ url_for('card.reject', card_id=data.id, _method='POST') }}" method="POST">
              <button class="btn btn-danger">거절</button>
            </form>
          </fieldset>
        </div>
      </div>
    </div>
{% endblock body %}

ybs/templates/card/create.html
{% extends "base/base.html" %}

{% block title %}
  Upload
{% endblock title %}

{% block body %}
    {{ super() }}
    <div class="container">
      <div class="common-form-container">
        <form class="form common-form" action="{{ url_for('card.create')}}" method="POST" enctype="multipart/form-data">
          {%- formfill data.form with data.error_dict -%}
          <fieldset>
            <div class="legend">
              <legend>업로드</legend>  
            </div>

            <div class="form-group">
              <!-- Name -->
              <label for="ybs-form-name">이름</label>
              <input type="text" id="ybs-form-name" name="name" placeholder="이름" class="form-control">
            </div>

            <div class="form-group">
              <!-- Message -->
              <label for="ybs-form-message">메시지</label>
              <textarea name="message" id="ybs-form-message" rows="5" class="form-control"></textarea>
            </div>
            <label for="ybs-form-photo">사진</label>
            <div class="form-group">
              <!-- Photo -->
              <input id="ybs-form-photo" type="file" name="photo" />
            </div>
          </fieldset>
          <fieldset>
            <!-- Button -->
            <button class="btn btn-success">업로드</button>
          </fieldset>
          {%- endformfill -%}
        </form>
        </div>
    </div>
{% endblock body %}

ybs/templates/card/index.html
{% extends "base/base.html" %}

{% block title %}
  List
{% endblock title %}

{% block js %}
{{ super() }}
<script language="javascript">
$(document).ready(function() {
});
</script>
{% endblock js %}

{% block css %}
{{ super() }}
<style type="text/css">
  td img {
      height: 30px;
      width:auto;
  }
</style>
{% endblock css %}

{% block body %}
  {{ super() }}
  <div class="container">
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th>ID</th>
          <th>Thumbnail</th>
          <th>Name</th>
          <th>Message</th>
          <th>Confirmed</th>
          <th>Rejected</th>
        </tr>
      </thead>
      <tbody>
        {% for card in data %}
        <tr>
          <td><a href="{{ url_for('card.read', card_id=card.id) }}">{{ card.id|safe }}</a></td>
          <td><a href="{{ url_for('card.read', card_id=card.id) }}">{{ card.photo.get_thumbnail('small') }}</a></td>
          <td><a href="{{ url_for('card.read', card_id=card.id) }}">{{ card.name|safe }}</a></td>
          <td><a href="{{ url_for('card.read', card_id=card.id) }}">{{ card.message|safe|truncate(50, True) }}</a></td>
          <td><a href="{{ url_for('card.read', card_id=card.id) }}">{{ card.is_confirmed|safe }}</a></td>
          <td><a href="{{ url_for('card.read', card_id=card.id) }}">{{ card.is_rejected|safe }}</a></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
      <div id="spin"/>
  </div>
{% endblock body %}

ybs/templates/card/nothing.html
{% extends "base/base.html" %}

{% block title %}
  Confirm
{% endblock title %}

{% block js %}
<script language="javascript">
function refresh() {
    window.location.reload(true);
}

setTimeout(refresh, 5 * 1000);
</script>
{% endblock js %}

{% block body %}
    {{ super() }}
    <div class="container" style="text-align:center;">
      <p>Nothing to confirm</p>
      <a href="{{ request.url }}"><button class="btn btn-primary">Refresh</button></a>
    </div>
{% endblock body %}

ybs/templates/card/read.html
{% extends "base/base.html" %}

{% block title %}
  Confirm
{% endblock title %}

{% block css %}
{{super()}}
{% endblock css %}

{% block body %}
    {{ super() }}
    <div class="container">
      <div class="common-form-container">
        <div class="form common-form" id="ybs-form-confirm">
          <fieldset>
            <div class="legend">
              <legend>Detail</legend>  
            </div>

            <div class="form-group">
              <!-- Name -->
              <label for="ybs-form-status">상태</label>
              <div>
                {% if data.is_rejected %}
                  거절됨
                {% elif data.is_confirmed %}
                  승인됨
                {% else %}
                  확인안됨
                {% endif %}
              </div>
            </div>
            <div class="form-group">
              <!-- Name -->
              <label for="ybs-form-name">이름</label>
              <div>
                {{ data.name|safe }}
              </div>
            </div>

            <div class="form-group">
              <!-- Message -->
              <label for="ybs-form-message">메시지</label>
              <div>
                {{ data.message|safe }}
              </div>
            </div>

            <div class="form-group">
              <!-- Message -->
              <label for="ybs-form-photo">사진</label>
              <div style="text-align: center;">
                {{ data.photo.original }}
              </div>
            </div>

            <div class="form-group">
              <!-- Message -->
              <label for="ybs-form-photo">정사각형 사진</label>
              <div style="text-align: center;">
                {{ data.photo.get_thumbnail('large') }}
              </div>
            </div>

          </fieldset>
          <fieldset>
            <!-- Button -->
            <form class="inline-form" action="{{ url_for('card.delete', card_id=data.id, __method__='DELETE') }}" onsubmit="return confirm('Do you really want to delete this card?');" method="POST">
              <button class="btn btn-danger">삭제</button>
            </form>
          </fieldset>
        </div>
      </div>
    </div>
{% endblock body %}

ybs/templates/card/uploaded.html
{% extends "base/base.html" %}

{% block title %}
  Upload
{% endblock title %}

{% block body %}
    {{ super() }}
    <div class="container">
      <p style="text-align:center;">업로드됬어여</p>
    </div>
{% endblock body %}